### PR TITLE
Upgrade to v15

### PR DESCRIPTION
**Pull request by shaharkazaz**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by NetanelBasal — APPROVED** [review]

**Comment by InYourHead** [comment]
Hello @shaharkazaz ,
your merge destroyed compatibility with angular 13:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myapp@0.0.0
npm ERR! Found: @angular/core@13.3.12
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^13.1.0" from the root project
npm ERR!   peer @angular/core@"^13.1.0" from myapp-lib@0.0.0-release-candidate-0-27.3
npm ERR!   node_modules/myapp-lib
npm ERR!     myapp-lib@"0.0.0-release-candidate-0-27.3" from the root project
npm ERR!   14 more (@angular-material-extensions/password-strength, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@">=14" from @ngneat/overview@4.0.0
npm ERR! node_modules/@ngneat/overview
npm ERR!   peer @ngneat/overview@">=3.0.0" from @ngneat/helipopper@5.1.4
npm ERR!   node_modules/@ngneat/helipopper
npm ERR!     peer @ngneat/helipopper@"^5.1.4" from myapp-lib@0.0.0-release-candidate-0-27.3
npm ERR!     node_modules/myapp-lib
npm ERR!       myapp-lib@"0.0.0-release-candidate-0-27.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /tmp/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/.npm/_logs/2023-01-23T10_02_29_721Z-debug-0.log
```

**Comment by shaharkazaz** [comment]
@InYourHead please read the changelog next time.
A major version release means that a breaking change was made.
From v4 overview has a peer dependency of angular v14.

**Comment by InYourHead** [comment]
I will try again to reproduce my issue:

Before this update my package.json look like this:

```
{
  "name": "myapp-lib",
  "version": "0.0.20",
  "peerDependencies": {
    [...]
    "@angular/core": "^13.1.0",
    "@angular/forms": "^13.1.0",
    [..]
    "@ngneat/helipopper": "^5.1.4",
    "@ngneat/overview": "^3.0.4",
  },
  "dependencies": {
    [...]
  },
 [..]
}
```

with dependant app:


```
{
  "name": "myapp",
  "version": "0.0.20",
  "scripts": {
   [...]
  },
  "engines": {
    "node": ">=16.13.2",
    "npm": ">=8.1.2"
  },
  "private": true,
  "dependencies": {
   [...]
    "myapp-lib" : "0.0.20",
    [..]
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^13.1.3",
    "@angular/cli": "^13.1.3",
    "@angular/compiler-cli": "^13.1.0",
    [..],
    "typescript": "~4.5.2"
  }
}
```

After this update ```@ngneat/overview``` is resolved as version 4.x.x, no matter do I set here:
```
  "@ngneat/overview": "<4.0.0",
```

or:
```
  "@ngneat/overview": "3.x.x",
```

Given error occurs. Do you know how could I fix this issue?

**Comment by shaharkazaz** [comment]
@InYourHead please open a discussion let's not spam this thread.

**Pull request merged**
